### ISSUE TITLE
is desktop  platform supported?

### ISSUE THREAD

**Issue by richard457** [Keyri-Co/flutter-keyri#27]

**Comment by zainazeem** [comment]
We currently do not support desktop platforms. We may consider adding support for desktop TPMs in the future. For now, the Keyri Flutter library is exclusively for use on mobile platforms.

**Comment by zainazeem** [comment]
If you wanted to use the Flutter SDK in your desktop app for device fingerprinting or fraud prevention, you can instead use our javascript agent within a webview component: https://github.com/Keyri-Co/xray
